# cloudbuild.yaml
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'asia-southeast2-docker.pkg.dev/haryo-kebakaran/wildfire-detector-ts/wildfire-detector-ts:latest',
    '-f', 'src/ml_model/Dockerfile', # Path to your Dockerfile from project root
    '.'  # Build context is the project root (where this cloudbuild.yaml is)
  ]
images:
- 'asia-southeast2-docker.pkg.dev/haryo-kebakaran/wildfire-detector-ts/wildfire-detector-ts:latest' # This ensures the image is pushed
options:
  machineType: 'E2_HIGHCPU_8' # Using E2_HIGHCPU_8 (8 vCPUs, 8 GB RAM)
timeout: '1800s' # 30 minutes (should be more than enough)
