# cloudbuild-image-processor.yaml
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    # Update paths to match new directory name
    mkdir -p deploy_staging/image_processor
    cp src/cloud_functions/image_processor/main.py deploy_staging/image_processor/main.py
    cp src/cloud_functions/image_processor/requirements.txt deploy_staging/image_processor/requirements.txt
    # Copy the shared 'src' directory so the acquirer can be imported
    cp -r src deploy_staging/image_processor/src

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
  - 'functions'
  - 'deploy'
  - 'ImageProcessorCF'
  - '--gen2'
  - '--runtime=python311'
  - '--region=asia-southeast2'
  - '--source=./deploy_staging/image_processor'
  - '--entry-point=image_processor_cloud_function'
  - '--trigger-topic=wildfire-cluster-detected'
  - '--service-account=fire-app-vm-service-account@haryo-kebakaran.iam.gserviceaccount.com'
  # --- THE ONLY CHANGE IS ON THIS LINE ---
  - '--set-env-vars=GCP_PROJECT_ID=haryo-kebakaran,GCP_REGION=asia-southeast2,GCS_BUCKET_NAME=fire-app-bucket,VERTEX_AI_OBJECT_DETECTION_MODEL=wildfire-cpr-predictor-model'
  - '--timeout=540s'
  - '--memory=2GiB'
  - '--project=haryo-kebakaran'

options:
  logging: CLOUD_LOGGING_ONLY
timeout: '1200s'
